version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=quote_service
    ports:
      - '5432:5432'
    volumes:
      - ./logback-init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    healthcheck:
      test: pg_isready -U admin -d quote_service
      interval: 5s

  quote_service:
#    container_name: quote_service_app
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: figazin/challenge-quote_service
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/quote_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      psql-db:
        condition: service_healthy